### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by LHDi**
* Make body bg black
* Make whole question clickable in accordion
* Delay blurriness of stacked cards
* Improvements to the code preview section

### CODE REVIEW

**Comment by jph00** [comment]
Thanks @LHDi !

**Comment by LHDi** [comment]
Hey @jph00, can you elaborate more on what these changes break? I tested it locally and it was working perfectly!

**Comment by jph00** [comment]
The index.html worked, but not main.py. I found the reason -- the generated
tailwind css was for the index.html file, not for the main.py file.

**Comment by LHDi** [comment]
Even the main.py worked for me @jph00 , that's weird 🤔

**Comment by LHDi** [comment]
Hey @jph00, how do you create tailwind.css file from the main.py? I can fix that if you want and make a PR to the new repo 🙏

**Comment by jph00** [comment]
Thanks for the offer! I actually got it all sorted out. I just manually
saved the index.html of the rendered page and re-generated the css. (In the
future I plan to create something to automate this in FastHTML directly.)

**Comment by LHDi** [comment]
That would be great actually. Can you also minify the CSS file @jph00, it would save some loading time.
You can use any online tools.

**Comment by jph00** [comment]
Yes will minify before we launch -- left it unminified for now since the
tinloof version wasn't minified so tried to keep things consistent.

**Pull request merged**
